### ISSUE TITLE
support for devDependencies?

### ISSUE THREAD

**Issue by ralphtheninja** [doowb/dependents-cli#5]

**Comment by doowb** [comment]
I've thought of this too.

I'm running a service where I keep track of dependents, devDependents, dependencies, and devDependencies of all modules (basically by monitoring the couchdb changes stream). It's also using `leveldb` 😀 .

I haven't opened it up to outside connections yet, mainly because I'm running it on my home network, but I was just working on moving that and some other services into the "cloud".

In the meantime, you can signup [here](https://doowb.com/npm-dependents) and I'll add you to the users whitelist. You won't see anything until I add you, but once I do, you can find the dependency information for any module.

If you want to get the download-counts for an individual repository, you can use the [downloads-cli](https://github.com/doowb/downloads-cli). This uses the [downloads](https://github.com/doowb/downloads) module, then does some aggregations for last 30 days. You can also use the `downloads-cli` as a module so you can iterate over an array of modules to get the stats for all of them.

Once I get the service opened up, I'll be able to update this lib so it's easier to access. If you have any suggestions (or feedback), let me know.

**Comment by ralphtheninja** [comment]
Sounds like an awesome service! Do you accept bitcoin donations?

**Comment by doowb** [comment]
Thanks!

> Do you accept bitcoin donations?

I'd appreciate that, but it's not necessary. However, I'll consider adding something to the site if it's used more than I expect.

**Comment by ralphtheninja** [comment]
> In the meantime, you can signup here and I'll add you to the users whitelist. You won't see anything until I add you, but once I do, you can find the dependency information for any module.

Signed up!

**Comment by ralphtheninja** [comment]
Btw, something completely unrelated. I like the way you are building your READMEs. Any info on that that I can read up on? How does it work with apidocs, .verb.md etc? Would be really nice to get a quick overview how it works.

**Comment by doowb** [comment]
> Signed up!

I added you so you should be able to access the data now.

> Any info on that that I can read up on?

We use [verb (the dev branch)](https://github.com/verbose/verb/tree/dev) and [verb-generate-readme](https://github.com/verbose/verb-generate-readme). The README on `verb-generate-readme` should have information on getting started.

Install the `dev` branch of `verb` and `verb-generate-readme`:

```sh
npm i -g verbose/verb#dev verb-generate-readme
```

Once those are installed, I run the following commands

```sh
# first time running verb will prompt to create a .verb.md file
verb
# initialize configuration settings (these go in package.json)
verb --init
```

Then I add the following to the .verb.md

```
# API
{%= apidocs('index.js') %}
```

The `apidocs` helper parses the code comments out of the javascript file and renders them into markdown syntax in the README.md. Look at most of our modules and you'll see how they work, but the simpliest example is this:

````js
/**
 * Some description goes here
 * ```js
 * // followed by some code example
 * ```
 * @param  {type} `varname` when function parameters following the example
 * @return {type} And an optional return line
 * @api public
 */
function foo(varname) {}
````

 Run `verb` again and it should generate your README.md with the api documentation. If nothing shows up, make sure the functions that you want to be shown have an `@api public` line.

We've been using it for our projects for a long time and helps speed up maintenance of our modules. If you need to change default templates take a look at `verb-generate-readme` and if you run into any issues, please feel free to open them [here](https://github.com/verbose/verb-generate-readme).

**Comment by jonschlinkert** [comment]
> We've been using it for our projects for a long time and helps speed up maintenance of our modules.

we should publish the dev branch on verb. I have avoided doing it because we haven't had time to do the docs. But as @doowb says, we use it a lot and it's been pretty stable for a while.

**Comment by ralphtheninja** [comment]
Thanks for your time and input guys!

**Comment by vweevers** [comment]
> In the meantime, you can signup here and I'll add you to the users whitelist. You won't see anything until I add you, but once I do, you can find the dependency information for any module.

@doowb that is awesome! Mind if I sign up too? Would happily donate as well.

I'd like to find the top devDependents of `zuul`. To assess popularity, whether it's worth investing in, and who would be affected by [changes](https://github.com/defunctzombie/zuul/pull/323#issuecomment-333371105) that I (and @ralphtheninja, coincidentally) would like to make to `zuul`. It *seems* many people prefer `karma` nowadays.

**Comment by doowb** [comment]
@vweevers you've been added! You should be able to log in now.

**Comment by vweevers** [comment]
Much obliged!
